/**
  Tests for Global Account View
*/
@isTest
public class CountryListAccTest {

    @testSetup
    static void setup() {
        // insereting opps domains contracts etc.
    }

    @isTest
    public static void shouldLoadAllAccountsByName() {
        Test.startTest();
        
        Test.stopTest();
    }

    @isTest
    public static void shouldLoadRecordsConnectedWithChoosenAccount() {
        Test.startTest();
        
        Test.stopTest();
    }
}