@isTest
public class HQAdminReportsTest {

    @isTest
    public static void shouldLoadFacetList() {
        
    }

    @isTest
    public static void shouldSaveNewFilters() {
        
    }

    @isTest
    public static void shouldFetchDomains() {
        
    }

    @isTest
    public static void shouldFilterDomains() {
        
    }

    @isTest
    public static void shouldFilterFacets() {
        
    }
}